# fly.toml app configuration file generated for maiella on 2024-10-20T10:19:36+02:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'maiella'
primary_region = 'iad'

[build]

[[vm]]
  size = "shared-cpu-1x"
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
